### ISSUE TITLE
Logitech Pen cannot be detected in the Openbrush Project

### ISSUE THREAD

**Issue by cz2011301070** [icosa-gallery/open-brush#413]
I can see my logitech pen in the SteamVR home. However, I cannot see the pen while running the Main scene in the Openbrush Project

**Comment by cz2011301070** [comment]
I compared the DetectLogitechVrPen.cs with the earlier version of this script which used steamVR and openVR. I found the all code inside the function IsLogitechPen(uint deviceIndex) is commented out. 

This IsLogitechPen(uint deviceIndex) is called by the Initialize function, which is called by InputManager.cs to detect the pen in the older version. However, the Initialze function is not called by any other script.

**Comment by mikeskydev** [comment]
Unfortunately Logitech does not provide an input profile for OpenXR, so therefore it currently can't be used with Open Brush 2.0. We have talked to Logitech and they don't plan to implement one at this time, if not ever, sadly.

As this would have blocked the release and due to the low number of users, we chose to remove support at this time, apologies for that. We are considering methods that would re-enable support for the Pen, including creating a custom SteamVR plugin that provides the input profile we'd require to detect the Pen from Unity. I will create an issue with a list of possible steps.

If you still wish to use the Pen, you can switch to the 'previous' beta branch on Steam which targets Open Brush 1.0.

**Comment by mikeskydev** [comment]
Closing this in favour of the full writeup in #416
